version: '3.8'

services:
  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - '${REDIS_PORT}:6379'
    command: redis-server --requirepass ${REDIS_PASSWORD}

  mongo:
    image: mongo:7.0.5
    restart: always
    ports:
      - '${DATABASE_PORT}:27017'
    volumes:
      - nestjs-template-mongo-db:/data/db

volumes:
  nestjs-template-mongo-db:
